### ISSUE TITLE
CM11 M9 Text garbled when script launch outside application

### ISSUE THREAD

**Issue by binkybear** [jackpal/Android-Terminal-Emulator#353]
A previous Android application I created will open/launch a script in Terminal on CM11 M8 but on M9 release the text appears garbled when sent to the emulator.  Running the su command the terminal outputs: 2;213R instead of su.  This occurred on both the Nexus 7 (2012) and the Nexus 10 using M9.

I've tried changing keyboards but I'm still unsure on where the error is occurring or how to fix it. 

Here is the logcat:

D/AudioPolicyManagerBase(  135): startOutput() output 2, stream 1, session 15
I/ActivityManager(  492): START u0 {act=jackpal.androidterm.RUN_SCRIPT cat=[android.intent.category.DEFAULT] cmp=jackpal.androidterm/.RunScript (has extras)} from pid 2196
I/TermService( 2226): Activity binding to service
I/ActivityManager(  492): START u0 {act=jackpal.androidterm.private.OPEN_NEW_WINDOW cat=[android.intent.category.DEFAULT] flg=0x10000000 cmp=jackpal.androidterm/.TermInternal} from pid 2226
D/mali_winsys( 2226): new_window_surface returns 0x3000
I/Timeline(  492): Timeline: Activity_windows_visible id: ActivityRecord{420cbfa8 u0 jackpal.androidterm/.RunScript t3 f} time:72145317
D/mali_winsys( 2226): new_window_surface returns 0x3000
I/Term    ( 2226): waiting for: 2289
I/HK/LatinKeyboardBaseView(  677): closing org.pocketworkstation.pckeyboard.LatinKeyboardView{428dc118 V.ED.... ......ID 0,0-2560,675 #7f07000a app:id/LatinkeyboardBaseView}
I/HK/LatinKeyboardBaseView(  677): closing org.pocketworkstation.pckeyboard.LatinKeyboardView{428dc118 V.ED.... ......ID 0,0-2560,675 #7f07000a app:id/LatinkeyboardBaseView}
I/HK/LatinKeyboardBaseView(  677): onMeasure width=2560
I/HK/LatinKeyboardBaseView(  677): onMeasure width=2560
I/Keyboard(  677): setKeyboardWidth newWidth=2560, mTotalWidth=2560
I/Timeline( 2226): Timeline: Activity_idle id: android.os.BinderProxy@41d5b348 time:72145598
I/Timeline(  492): Timeline: Activity_windows_visible id: ActivityRecord{41dad718 u0 jackpal.androidterm/.TermInternal t4} time:72145644

**Comment by peterpt** [comment]
an update : i installed everything from the beginning , latest CM rom on tablet  , following the procedures of root the tablet with nexus 7 toolkit , i installed SU and busybox free , and then after that before i install anything else i installed nethunter image .
i run kali shell and kali menu and everything is working great .
here it is the pictures 

http://s28.postimg.org/ei61feqnx/capture1.png
http://s7.postimg.org/3vyqz88ff/capture2.png
http://s29.postimg.org/oi2n1s3sn/capture3.png
http://s7.postimg.org/b4ez29ajv/capture4.png
http://s8.postimg.org/mjmvtgfg5/capture5.png
http://s2.postimg.org/8wt8ynh2h/capture6.png
http://s28.postimg.org/tuyz0x4l9/capture7.png

**Comment by binkybear** [comment]
https://github.com/offensive-security/kali-nethunter/commit/9f58321a859ee10d71c70ec0e2fb6e49dafa5436 I was able to narrow down where the error was occurring ( resize is called from /system/etc/mkshrc).  I noticed on stock resize is never called from mkshrc, only cyanogenmod calls it.  It can be safely removed and it will fix this error, although I will leave it up to developer to close this issue or not.

I removed that line during latest install of nethunter so it should be fixed for nethunter.

**Comment by peterpt** [comment]
for those who still have the previous image of nethunter installed , the best way to get around this issue it to get "root browser" , then navigate to your /system/xbin" folder and remove (resize) file .
to run kali terminal after that error without fixing it , you just need to apply these commands after the error 
su
bootkali

and kali root terminal should popup

**Comment by FrankWestlake** [comment]
'binkybear' said:
  I was able to narrow down where the error was occurring 
  ( resize is called from /system/etc/mkshrc).

'resize' is not in the script '/system/etc/mkshrc' on my SM-N900T (Note3) so this doesn't appear to be a general problem. 

'binkybear' said:
  ...I will leave it up to developer to close this issue or not.

Please be kind to the developer. No one is more familiar with this issue than you are and the developer might have too study it completely to determine if it should be closed. You initiated this issue so only you and the developer can close it; if it is your opinion that this issue is not caused by this application and that this application should not be changed to compensate then please close it. 

Frank

**Comment by binkybear** [comment]
@FrankWestlake 

Good point.  The issue is not caused Terminal Emulator but is caused by Cyanogenmod calling resize from mkshrc.  I will close the issue and if others run into this issue hopefully they will learn the soluton from the problem here.

Thanks Frank and everyone else who else who worked on this.

**Comment by JustArchi** [comment]
Note: It doesn't happen on Lollipop CM.
